FROM node:22.12.0-alpine AS build

WORKDIR /app

RUN npm install -g @angular/cli@19.2.3

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN ng build 

FROM node:22.12.0-alpine

WORKDIR /app   

RUN npm install -g serve@14.2.1

COPY --from=build /app/dist/frontend/browser ./dist  

EXPOSE 4200

CMD ["serve", "-s", "dist", "-l", "4200"]