version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hiberus-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - hiberus-network
    restart: unless-stopped
    volumes:
      - backend-data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: hiberus-frontend
    ports:
      - "4200:4200"
    networks:
      - hiberus-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  hiberus-network:
    driver: bridge

volumes:
  backend-data: